---
- name: Install network utilities
  become: true
  ansible.builtin.apt:
    name: "{{ net_utils_packages }}"
    state: present
    update_cache: true
    cache_valid_time: 3600
    install_recommends: false
