name: Python

on:
  # Run on all branch pushes to ensure tests always run
  push:
  # All pull requests trigger the workflow
  pull_request:
  release:
    types: [published]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          uv pip install -e .
          uv pip install -r requirements/requirements-hatch-test.py3.11.txt

      - name: Run unit tests
        run: |
          pytest tests/ --cov=src --cov-report=xml

      - name: Build package
        run: |
          uv pip install build wheel
          python -m build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-python-${{ matrix.python-version }}
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'release'
    name: Publish Package

    # Note: To use environments for PyPI publishing, you would need to:
    # 1. Create a 'release' environment in GitHub repository settings
    # 2. Add 'environment: release' here
    # For now, we'll use trusted publishing with OIDC
    permissions:
      id-token: write # Required for trusted publishing

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          merge-multiple: true
          path: dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
